"""Render a lockfile as a ``docker-compose.yml`` snippet.

Emits a single ``comfyui`` service with volume mounts for the model directories
the lock needs, the pinned core commit recorded as metadata, and a *commented*
block of ``git clone`` lines for the custom nodes (opt-in, like the Dockerfile
exporter -- the compose file never executes untrusted clones for you).

A lockfile is third-party input, so every interpolated value is one-lined and
either YAML-quoted (data) or shell-quoted (the commented clone commands).
"""

from __future__ import annotations

import shlex

from .. import __version__
from ..model import Lockfile


def _oneline(value: object) -> str:
    return str(value).replace("\r", " ").replace("\n", " ")


def _yaml_str(value: object) -> str:
    """A safe double-quoted YAML scalar (escape ``\\`` and ``"``, collapse NL)."""
    text = _oneline(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def _arg(value: object) -> str:
    return shlex.quote(_oneline(value))


def _node_name(url: str) -> str:
    seg = url.rstrip("/").replace("\\", "/").rstrip("/").split("/")[-1]
    return seg[:-4] if seg.endswith(".git") else seg


def _model_dirs(lock: Lockfile) -> list[str]:
    """Unique top-level model subdirectories referenced by the lock paths."""
    dirs: dict[str, None] = {}
    for m in lock.models:
        rel = m.paths[0] if m.paths else f"models/{m.type or 'checkpoints'}/{m.name}"
        rel = rel.replace("\\", "/")
        parts = rel.split("/")
        # keep the directory portion, drop the filename
        directory = "/".join(parts[:-1]) if len(parts) > 1 else "models"
        if directory:
            dirs.setdefault(directory, None)
    return sorted(dirs)


def to_docker_compose(lock: Lockfile) -> str:
    out: list[str] = []
    out.append("# Generated by ComfyLock -- https://github.com/theot44240-tech/comfylock")
    out.append(f"# comfylock {__version__}")
    if lock.workflow:
        out.append(f"# workflow: {_oneline(lock.workflow)}")
    out.append('services:')
    out.append('  comfyui:')
    out.append('    image: "comfyanonymous/comfyui:latest"')
    out.append('    container_name: "comfyui"')
    out.append('    ports:')
    out.append('      - "8188:8188"')
    out.append('    working_dir: "/ComfyUI"')
    out.append('    volumes:')
    out.append('      - "./models:/ComfyUI/models"')
    out.append('      - "./custom_nodes:/ComfyUI/custom_nodes"')
    out.append('    command: ["python", "main.py", "--listen", "0.0.0.0"]')

    labels: list[str] = [f'      comfylock.version: {_yaml_str(__version__)}']
    if lock.comfyui:
        labels.append(f'      comfylock.comfyui_commit: {_yaml_str(lock.comfyui)}')
    if lock.workflow:
        labels.append(f'      comfylock.workflow: {_yaml_str(lock.workflow)}')
    out.append('    labels:')
    out.extend(labels)

    model_dirs = _model_dirs(lock)
    if model_dirs:
        out.append("")
        out.append("# Model directories this lock expects under ./models:")
        for d in model_dirs:
            out.append(f"#   - {_oneline(d)}")

    if lock.comfyui:
        out.append("")
        out.append("# Pin ComfyUI core (run inside the container or bake into an image):")
        out.append(f"#   git -C /ComfyUI fetch --all && git -C /ComfyUI checkout {_arg(lock.comfyui)}")

    if lock.git_nodes:
        out.append("")
        out.append("# Custom nodes (pinned). Uncomment to install into ./custom_nodes:")
        for url, commit in sorted(lock.git_nodes.items()):
            name = _node_name(url)
            out.append(
                f"#   git clone {_arg(url)} custom_nodes/{_arg(name)} && "
                f"git -C custom_nodes/{_arg(name)} checkout {_arg(commit)}"
            )
    return "\n".join(out) + "\n"
