"""Render a lockfile as a reproducible Dockerfile.

Model downloads are emitted as commented ``# wget`` stubs by default (so the
image stays small and the build never pulls tens of GB unexpectedly), but the
exact URL and a hash-verify command are shown for each so a user can opt in.
"""

from __future__ import annotations

from .. import __version__
from ..model import Lockfile


def _node_name(url: str) -> str:
    seg = url.rstrip("/").replace("\\", "/").rstrip("/").split("/")[-1]
    return seg[:-4] if seg.endswith(".git") else seg


def to_dockerfile(lock: Lockfile) -> str:
    out: list[str] = []
    out.append("# syntax=docker/dockerfile:1")
    out.append("# Generated by ComfyLock -- https://github.com/theot44240-tech/comfylock")
    out.append("FROM comfyanonymous/comfyui:latest")
    out.append(f'LABEL comfylock.version="{__version__}"')
    if lock.workflow:
        out.append(f'LABEL comfylock.workflow="{lock.workflow}"')
    out.append("")
    out.append("WORKDIR /ComfyUI")
    out.append("")

    if lock.comfyui:
        out.append("# Pin ComfyUI core to the locked commit")
        out.append(f"RUN git fetch --all && git checkout {lock.comfyui}")
        out.append("")

    if lock.git_nodes:
        out.append("# Custom nodes (pinned commits)")
        out.append("WORKDIR /ComfyUI/custom_nodes")
        for url, commit in sorted(lock.git_nodes.items()):
            name = _node_name(url)
            out.append(
                f"RUN git clone {url} {name} && "
                f"cd {name} && git checkout {commit}"
            )
        out.append("WORKDIR /ComfyUI")
        out.append("")

    if lock.models:
        out.append("# Models -- commented out by default to keep the image small.")
        out.append("# Uncomment the lines you need; each is followed by a hash check.")
        for m in sorted(lock.models, key=lambda m: m.name.lower()):
            dest = m.paths[0] if m.paths else f"models/checkpoints/{m.name}"
            sha = m.hash_of("SHA256")
            if not m.url:
                out.append(f"# (no download URL for {m.name})")
                continue
            out.append(f"# {m.name} ({m.type or 'model'})")
            out.append(f"# RUN mkdir -p $(dirname {dest}) && wget -O {dest} '{m.url}'")
            if sha:
                out.append(f"# RUN echo '{sha}  {dest}' | sha256sum -c -")
        out.append("")

    out.append('CMD ["python", "main.py", "--listen", "0.0.0.0"]')
    return "\n".join(out) + "\n"
