"""Render a lockfile as a Markdown report (great for forum/Civitai posts)."""

from __future__ import annotations

from ..inspect import human_size
from ..model import Lockfile


def _node_name(url: str) -> str:
    seg = url.rstrip("/").replace("\\", "/").rstrip("/").split("/")[-1]
    return seg[:-4] if seg.endswith(".git") else seg


def to_markdown(lock: Lockfile) -> str:
    out: list[str] = []
    title = lock.workflow or "ComfyUI workflow"
    out.append(f"# {title} — ComfyLock")
    out.append("")
    meta = [f"schema v{lock.version}"]
    if lock.comfylock_version:
        meta.append(f"comfylock {lock.comfylock_version}")
    if lock.generated:
        meta.append(f"generated {lock.generated}")
    out.append("> " + " · ".join(meta))
    out.append("")

    out.append("## ComfyUI core")
    out.append("")
    out.append(f"- commit `{lock.comfyui or '(not pinned)'}`")
    out.append("")

    out.append("## Custom nodes")
    out.append("")
    if lock.git_nodes or lock.file_nodes:
        for url, commit in sorted(lock.git_nodes.items()):
            out.append(f"- [{_node_name(url)}]({url}) @ `{commit[:10]}`")
        for fn in sorted(lock.file_nodes, key=lambda f: f.filename):
            state = " _(disabled)_" if fn.disabled else ""
            out.append(f"- `{fn.filename}`{state}")
    else:
        out.append("_None._")
    out.append("")

    out.append("## Models")
    out.append("")
    if lock.models:
        out.append("| Name | Type | Size | SHA256 | Download |")
        out.append("| --- | --- | --- | --- | --- |")
        for m in sorted(lock.models, key=lambda m: m.name.lower()):
            sha = m.hash_of("SHA256") or ""
            sha_cell = f"`{sha[:12]}…`" if sha else "—"
            link = f"[link]({m.url})" if m.url else "—"
            out.append(
                f"| `{m.name}` | {m.type or ''} | {human_size(m.size)} | "
                f"{sha_cell} | {link} |"
            )
    else:
        out.append("_None._")
    out.append("")

    if lock.parameters:
        out.append("## Parameters")
        out.append("")
        for k, v in sorted(lock.parameters.items()):
            out.append(f"- **{k}**: `{v}`")
        out.append("")

    out.append("---")
    out.append("")
    out.append(
        "Generated by [ComfyLock](https://github.com/theot44240-tech/comfylock) — "
        "`pip install comfylock`."
    )
    return "\n".join(out) + "\n"
