"""Render a lockfile as a standalone POSIX ``install.sh``.

Clones each pinned custom node at its commit and downloads each model (curl with
a wget fallback), verifying SHA256 via ``sha256sum``. No Python is needed to run
the output -- it is a portable bootstrap for a locked ComfyUI environment.
"""

from __future__ import annotations

from .. import __version__
from ..model import Lockfile


def _node_name(url: str) -> str:
    seg = url.rstrip("/").replace("\\", "/").rstrip("/").split("/")[-1]
    return seg[:-4] if seg.endswith(".git") else seg


def to_shell(lock: Lockfile) -> str:
    out: list[str] = []
    out.append("#!/usr/bin/env bash")
    out.append(
        f"# Generated by ComfyLock {__version__} -- "
        "https://github.com/theot44240-tech/comfylock"
    )
    out.append("# Reproduce a locked ComfyUI environment. Run from your ComfyUI root.")
    out.append("set -euo pipefail")
    out.append("")
    out.append('ROOT="${1:-$(pwd)}"')
    out.append('cd "$ROOT"')
    out.append("")
    out.append("dl() { # dl URL DEST -- download with curl, falling back to wget")
    out.append('  url="$1"; dest="$2"; mkdir -p "$(dirname "$dest")"')
    out.append('  if command -v curl >/dev/null 2>&1; then')
    out.append('    curl -fL --retry 3 -o "$dest" "$url"')
    out.append('  else')
    out.append('    wget -O "$dest" "$url"')
    out.append('  fi')
    out.append("}")
    out.append("")

    if lock.comfyui:
        out.append("# Pin ComfyUI core to the locked commit")
        out.append(f"git fetch --all && git checkout {lock.comfyui}")
        out.append("")

    if lock.git_nodes:
        out.append("# Custom nodes (pinned commits)")
        out.append('mkdir -p custom_nodes && cd custom_nodes')
        for url, commit in sorted(lock.git_nodes.items()):
            name = _node_name(url)
            out.append(f'if [ ! -d "{name}" ]; then git clone "{url}" "{name}"; fi')
            out.append(f'( cd "{name}" && git fetch --all && git checkout {commit} )')
        out.append('cd "$ROOT"')
        out.append("")

    if lock.models:
        out.append("# Models")
        for m in sorted(lock.models, key=lambda m: m.name.lower()):
            dest = m.paths[0] if m.paths else f"models/checkpoints/{m.name}"
            sha = m.hash_of("SHA256")
            if not m.url:
                out.append(
                    f'echo "WARN: no download URL for {m.name}; '
                    f'place it at {dest} manually"'
                )
                continue
            out.append(f'dl "{m.url}" "{dest}"')
            if sha:
                out.append(f'echo "{sha}  {dest}" | sha256sum -c -')
        out.append("")

    out.append('echo "ComfyLock: environment restored."')
    return "\n".join(out) + "\n"
